spring:
  application:
    name: wedding-planner-api
  datasource:
    url: jdbc:h2:file:./data/weddingdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 110MB
      max-request-size: 120MB

server:
  port: 18080

app:
  upload:
    dir: ./uploads
  jwt:
    secret: "wedding-planner-dev-secret-change-me-in-production-32chars-min"
    access-expiration-ms: 900000
    refresh-expiration-ms: 604800000
  cors:
    allowed-origins: "http://localhost:3000"
  seed:
    superadmin:
      email: superadmin@aisle.local
      password: SuperAdmin@123
      full-name: Super Admin

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security: INFO
