/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/weddings/{weddingId}/vendors/{vendorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/vendors/{vendorId}/payments/{paymentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updatePayment"];
        post?: never;
        delete: operations["deletePayment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/thank-you-card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["upsert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_1"];
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/seating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put: operations["save"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/registry/gifts/{giftId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateGift"];
        post?: never;
        delete: operations["deleteGift"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/registry/funds/{fundId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateFund"];
        post?: never;
        delete: operations["deleteFund"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/public-page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getForHost"];
        put: operations["updateForHost"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/guests/{guestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_2"];
        post?: never;
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/guests/bulk-rsvp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["bulkRsvp"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/gallery/photos/{photoId}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setApproval"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/gallery/albums/{albumId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_3"];
        post?: never;
        delete: operations["deleteAlbum"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/crew/{membershipId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_4"];
        post?: never;
        delete: operations["remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/invites/{token}/rsvp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["rsvp"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/vendors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/vendors/{vendorId}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/vendors/{vendorId}/payments/{paymentId}/mark-pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markPending"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/vendors/{vendorId}/payments/{paymentId}/mark-paid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markPaid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/registry/gifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createGift"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/registry/funds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createFund"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/registry/contributions/{contributionId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["updateContributionStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/guests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/guests/{guestId}/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ensureInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/guests/{guestId}/invite/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["regenerateInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/guests/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importCsv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/gallery/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_4"];
        put?: never;
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/gallery/albums/{albumId}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/crew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_5"];
        put?: never;
        post: operations["invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/check-in/{guestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["checkIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/weddings/{slug}/seat-finder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["seatFinder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/weddings/{slug}/rsvp-lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rsvpLookup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/weddings/{slug}/registry/gifts/{giftId}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["claim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/weddings/{slug}/registry/funds/{fundId}/contribute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["contribute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/invites/{token}/gallery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["guestContribute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["hostRegistry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/guests/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lookup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/check-in/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/weddings/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/weddings/{slug}/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["publicRegistry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/weddings/{slug}/gallery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["publicGallery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/invites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/invites/{token}/thank-you": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["publicCard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublic_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{weddingId}/gallery/photos/{photoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deletePhoto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpsertVendorRequest: {
            name: string;
            /** @enum {string} */
            category: "DJ" | "BAND" | "ASHTAKA" | "PHOTOGRAPHER" | "VIDEOGRAPHER" | "CATERER" | "FLORIST" | "DECORATOR" | "MAKEUP" | "TRANSPORT" | "VENUE" | "OTHER";
            /** @enum {string} */
            status: "PENDING" | "CONTACTED" | "BOOKED" | "CONFIRMED" | "CANCELLED";
            contactName?: string;
            email?: string;
            phone?: string;
            quotedAmount?: number;
            advanceAmount?: number;
            /** Format: date */
            advanceDueDate?: string;
            /** Format: date */
            remainingDueDate?: string;
            notes?: string;
        };
        VendorPaymentResponse: {
            /** Format: int64 */
            id?: number;
            label?: string;
            amount?: number;
            /** Format: date */
            dueDate?: string;
            /** Format: date */
            paidDate?: string;
            /** @enum {string} */
            status?: "PENDING" | "PAID" | "OVERDUE";
        };
        VendorResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            weddingId?: number;
            name?: string;
            /** @enum {string} */
            category?: "DJ" | "BAND" | "ASHTAKA" | "PHOTOGRAPHER" | "VIDEOGRAPHER" | "CATERER" | "FLORIST" | "DECORATOR" | "MAKEUP" | "TRANSPORT" | "VENUE" | "OTHER";
            /** @enum {string} */
            status?: "PENDING" | "CONTACTED" | "BOOKED" | "CONFIRMED" | "CANCELLED";
            contactName?: string;
            email?: string;
            phone?: string;
            quotedAmount?: number;
            advanceAmount?: number;
            totalPaid?: number;
            remainingAmount?: number;
            /** Format: date */
            nextDueDate?: string;
            notes?: string;
            payments?: components["schemas"]["VendorPaymentResponse"][];
        };
        UpsertPaymentRequest: {
            label: string;
            amount: number;
            /** Format: date */
            dueDate?: string;
        };
        UpsertThankYouCardRequest: {
            templateKey?: string;
            message: string;
            signature?: string;
            imageUrl?: string;
        };
        ThankYouCardResponse: {
            /** Format: int64 */
            id?: number;
            templateKey?: string;
            message?: string;
            signature?: string;
            imageUrl?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        UpsertTaskRequest: {
            title: string;
            notes?: string;
            /** @enum {string} */
            status: "TODO" | "IN_PROGRESS" | "DONE";
            /** Format: date */
            dueDate?: string;
            /** Format: int64 */
            assigneeUserId?: number;
        };
        TaskResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            weddingId?: number;
            title?: string;
            notes?: string;
            /** @enum {string} */
            status?: "TODO" | "IN_PROGRESS" | "DONE";
            /** Format: date */
            dueDate?: string;
            /** Format: int64 */
            assigneeUserId?: number;
            assigneeName?: string;
        };
        JsonNode: {
            array?: boolean;
            empty?: boolean;
            null?: boolean;
            float?: boolean;
            number?: boolean;
            container?: boolean;
            floatingPointNumber?: boolean;
            missingNode?: boolean;
            valueNode?: boolean;
            /** @enum {string} */
            nodeType?: "ARRAY" | "BINARY" | "BOOLEAN" | "MISSING" | "NULL" | "NUMBER" | "OBJECT" | "POJO" | "STRING";
            object?: boolean;
            double?: boolean;
            integralNumber?: boolean;
            bigDecimal?: boolean;
            bigInteger?: boolean;
            int?: boolean;
            pojo?: boolean;
            string?: boolean;
            short?: boolean;
            long?: boolean;
            /** @deprecated */
            textual?: boolean;
            binary?: boolean;
            boolean?: boolean;
            embeddedValue?: boolean;
        };
        SaveSeatingRequest: {
            plan: components["schemas"]["JsonNode"];
            /** Format: int32 */
            version: number;
        };
        SeatingResponse: {
            /** Format: int64 */
            weddingId?: number;
            plan?: components["schemas"]["JsonNode"];
            /** Format: int32 */
            version?: number;
        };
        UpsertGiftItemRequest: {
            title: string;
            description?: string;
            imageUrl?: string;
            storeUrl?: string;
            priceAmount?: number;
            currency?: string;
            /** Format: int32 */
            quantityDesired?: number;
            /** Format: int32 */
            sortOrder?: number;
            publicVisible?: boolean;
        };
        GiftClaimResponse: {
            /** Format: int64 */
            id?: number;
            claimerName?: string;
            claimerEmail?: string;
            message?: string;
            createdAt?: string;
        };
        GiftItemResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            imageUrl?: string;
            storeUrl?: string;
            priceAmount?: number;
            currency?: string;
            /** Format: int32 */
            quantityDesired?: number;
            /** Format: int32 */
            quantityClaimed?: number;
            /** Format: int32 */
            remaining?: number;
            fullyClaimed?: boolean;
            /** Format: int32 */
            sortOrder?: number;
            publicVisible?: boolean;
            claims?: components["schemas"]["GiftClaimResponse"][];
        };
        UpsertCashFundRequest: {
            title: string;
            description?: string;
            goalAmount: number;
            currency?: string;
            imageUrl?: string;
            /** Format: int32 */
            sortOrder?: number;
            publicVisible?: boolean;
        };
        CashFundResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            goalAmount?: number;
            raisedAmount?: number;
            pendingAmount?: number;
            currency?: string;
            imageUrl?: string;
            /** Format: int32 */
            sortOrder?: number;
            publicVisible?: boolean;
            /** Format: double */
            progressPercent?: number;
        };
        UpdatePublicPageRequest: {
            coupleNames?: string;
            story?: string;
            heroImageUrl?: string;
            photoUrls?: string[];
            publicEnabled?: boolean;
        };
        WeddingPublicPageResponse: {
            /** Format: int64 */
            weddingId?: number;
            slug?: string;
            title?: string;
            coupleNames?: string;
            /** Format: date */
            weddingDate?: string;
            venue?: string;
            story?: string;
            heroImageUrl?: string;
            photoUrls?: string[];
            publicEnabled?: boolean;
        };
        UpsertGuestRequest: {
            fullName: string;
            email?: string;
            phone?: string;
            household?: string;
            mealPreference?: string;
            /** @enum {string} */
            rsvpStatus: "PENDING" | "ACCEPTED" | "DECLINED" | "MAYBE";
            tags?: string;
            tableLabel?: string;
            notes?: string;
        };
        GuestResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            weddingId?: number;
            fullName?: string;
            email?: string;
            phone?: string;
            household?: string;
            mealPreference?: string;
            /** @enum {string} */
            rsvpStatus?: "PENDING" | "ACCEPTED" | "DECLINED" | "MAYBE";
            tags?: string;
            tableLabel?: string;
            notes?: string;
            inviteToken?: string;
            /** @enum {string} */
            attendanceStatus?: "NOT_ARRIVED" | "ADMITTED" | "REJECTED";
            checkedInAt?: string;
        };
        GalleryPhotoResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            albumId?: number;
            uploadId?: string;
            imageUrl?: string;
            caption?: string;
            mediaType?: string;
            approved?: boolean;
            contributorName?: string;
            /** Format: int32 */
            sortOrder?: number;
        };
        UpsertAlbumRequest: {
            title: string;
            description?: string;
            /** Format: int32 */
            sortOrder?: number;
            publicVisible?: boolean;
        };
        GalleryAlbumResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            /** Format: int32 */
            sortOrder?: number;
            publicVisible?: boolean;
            photos?: components["schemas"]["GalleryPhotoResponse"][];
        };
        UpdateCrewRequest: {
            /** @enum {string} */
            role: "OWNER" | "COUPLE" | "CREW" | "VENDOR" | "GUEST";
            responsibilities?: string;
        };
        WeddingMemberResponse: {
            /** Format: int64 */
            membershipId?: number;
            /** Format: int64 */
            userId?: number;
            fullName?: string;
            email?: string;
            role?: string;
            responsibilities?: string;
        };
        PublicRsvpRequest: {
            /** @enum {string} */
            rsvpStatus: "PENDING" | "ACCEPTED" | "DECLINED" | "MAYBE";
            mealPreference?: string;
            notes?: string;
        };
        PublicInviteResponse: {
            token?: string;
            weddingTitle?: string;
            weddingDate?: string;
            venue?: string;
            guestName?: string;
            household?: string;
            mealPreference?: string;
            /** @enum {string} */
            rsvpStatus?: "PENDING" | "ACCEPTED" | "DECLINED" | "MAYBE";
            tableLabel?: string;
            seatLabel?: string;
            seatAssigned?: boolean;
            /** @enum {string} */
            attendanceStatus?: "NOT_ARRIVED" | "ADMITTED" | "REJECTED";
            checkedInAt?: string;
        };
        CreateWeddingRequest: {
            title: string;
            slug?: string;
            /** Format: date */
            weddingDate?: string;
            venue?: string;
        };
        WeddingResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            slug?: string;
            /** Format: date */
            weddingDate?: string;
            venue?: string;
            inviteCode?: string;
            membershipRole?: string;
        };
        UploadResponse: {
            id?: string;
            url?: string;
            contentType?: string;
            /** Format: int64 */
            sizeBytes?: number;
            originalFilename?: string;
        };
        CashContributionResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            fundId?: number;
            fundTitle?: string;
            contributorName?: string;
            contributorEmail?: string;
            amount?: number;
            message?: string;
            status?: string;
            createdAt?: string;
        };
        GuestImportResult: {
            /** Format: int32 */
            imported?: number;
            /** Format: int32 */
            skipped?: number;
            message?: string;
        };
        AddPhotoRequest: {
            uploadId?: string;
            imageUrl: string;
            caption?: string;
            mediaType?: string;
            /** Format: int32 */
            sortOrder?: number;
        };
        InviteCrewRequest: {
            /** Format: email */
            email: string;
            fullName?: string;
            /** @enum {string} */
            role: "OWNER" | "COUPLE" | "CREW" | "VENDOR" | "GUEST";
            responsibilities?: string;
        };
        InviteCrewResponse: {
            member?: components["schemas"]["WeddingMemberResponse"];
            createdNewUser?: boolean;
            tempPassword?: string;
        };
        CheckInActionRequest: {
            /** @enum {string} */
            action: "NOT_ARRIVED" | "ADMITTED" | "REJECTED";
        };
        CheckInGuestResponse: {
            /** Format: int64 */
            id?: number;
            fullName?: string;
            household?: string;
            /** @enum {string} */
            rsvpStatus?: "PENDING" | "ACCEPTED" | "DECLINED" | "MAYBE";
            tableLabel?: string;
            seatLabel?: string;
            inviteToken?: string;
            /** @enum {string} */
            attendanceStatus?: "NOT_ARRIVED" | "ADMITTED" | "REJECTED";
            checkedInAt?: string;
        };
        SeatFinderRequest: {
            guestName: string;
            tableLabel: string;
        };
        SeatFinderResponse: {
            matched?: boolean;
            message?: string;
            guestName?: string;
            tableLabel?: string;
            seatLabel?: string;
            /** @enum {string} */
            rsvpStatus?: "PENDING" | "ACCEPTED" | "DECLINED" | "MAYBE";
            /** @enum {string} */
            attendanceStatus?: "NOT_ARRIVED" | "ADMITTED" | "REJECTED";
        };
        PublicRsvpLookupRequest: {
            fullName: string;
            /** Format: email */
            email?: string;
        };
        PublicRsvpLookupResponse: {
            matched?: boolean;
            message?: string;
            inviteToken?: string;
            guestName?: string;
        };
        ClaimGiftRequest: {
            claimerName: string;
            /** Format: email */
            claimerEmail?: string;
            message?: string;
        };
        ContributeCashRequest: {
            contributorName: string;
            /** Format: email */
            contributorEmail?: string;
            amount: number;
            message?: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            fullName: string;
        };
        AuthResponse: {
            token?: string;
            refreshToken?: string;
            /** Format: int64 */
            expiresIn?: number;
            /** Format: int64 */
            userId?: number;
            email?: string;
            fullName?: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        HostRegistryResponse: {
            gifts?: components["schemas"]["GiftItemResponse"][];
            cashFunds?: components["schemas"]["CashFundResponse"][];
            contributions?: components["schemas"]["CashContributionResponse"][];
        };
        CheckInStatsResponse: {
            /** Format: int64 */
            totalGuests?: number;
            /** Format: int64 */
            admitted?: number;
            /** Format: int64 */
            rejected?: number;
            /** Format: int64 */
            notArrived?: number;
        };
        PublicWeddingResponse: {
            slug?: string;
            title?: string;
            coupleNames?: string;
            /** Format: date */
            weddingDate?: string;
            venue?: string;
            story?: string;
            heroImageUrl?: string;
            photoUrls?: string[];
            publicEnabled?: boolean;
        };
        PublicRegistryResponse: {
            gifts?: components["schemas"]["GiftItemResponse"][];
            cashFunds?: components["schemas"]["CashFundResponse"][];
        };
        PublicThankYouResponse: {
            templateKey?: string;
            message?: string;
            signature?: string;
            imageUrl?: string;
            guestName?: string;
            coupleNames?: string;
            weddingTitle?: string;
            weddingDate?: string;
        };
        MeResponse: {
            /** Format: int64 */
            id?: number;
            email?: string;
            fullName?: string;
            globalRole?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                vendorId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertVendorRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VendorResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                vendorId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updatePayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                vendorId: number;
                paymentId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertPaymentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VendorPaymentResponse"];
                };
            };
        };
    };
    deletePayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                vendorId: number;
                paymentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ThankYouCardResponse"];
                };
            };
        };
    };
    upsert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertThankYouCardRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ThankYouCardResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                taskId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertTaskRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                taskId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeatingResponse"];
                };
            };
        };
    };
    save: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveSeatingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeatingResponse"];
                };
            };
        };
    };
    updateGift: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                giftId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertGiftItemRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GiftItemResponse"];
                };
            };
        };
    };
    deleteGift: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                giftId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateFund: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                fundId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertCashFundRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CashFundResponse"];
                };
            };
        };
    };
    deleteFund: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                fundId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getForHost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WeddingPublicPageResponse"];
                };
            };
        };
    };
    updateForHost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePublicPageRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WeddingPublicPageResponse"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                guestId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertGuestRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GuestResponse"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                guestId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    bulkRsvp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setApproval: {
        parameters: {
            query: {
                approved: boolean;
            };
            header?: never;
            path: {
                weddingId: number;
                photoId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GalleryPhotoResponse"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                albumId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertAlbumRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GalleryAlbumResponse"];
                };
            };
        };
    };
    deleteAlbum: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                albumId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                membershipId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCrewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WeddingMemberResponse"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                membershipId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rsvp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicRsvpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PublicInviteResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WeddingResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWeddingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WeddingResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                category?: string;
                q?: string;
            };
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VendorResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertVendorRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VendorResponse"];
                };
            };
        };
    };
    addPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                vendorId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertPaymentRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VendorPaymentResponse"];
                };
            };
        };
    };
    markPending: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                vendorId: number;
                paymentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VendorPaymentResponse"];
                };
            };
        };
    };
    markPaid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                vendorId: number;
                paymentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VendorPaymentResponse"];
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UploadResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponse"][];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertTaskRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponse"];
                };
            };
        };
    };
    createGift: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertGiftItemRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GiftItemResponse"];
                };
            };
        };
    };
    createFund: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertCashFundRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CashFundResponse"];
                };
            };
        };
    };
    updateContributionStatus: {
        parameters: {
            query: {
                status: "PENDING" | "CONFIRMED" | "CANCELLED";
            };
            header?: never;
            path: {
                weddingId: number;
                contributionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CashContributionResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: {
                q?: string;
                rsvp?: string;
            };
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GuestResponse"][];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertGuestRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GuestResponse"];
                };
            };
        };
    };
    ensureInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                guestId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GuestResponse"];
                };
            };
        };
    };
    regenerateInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                guestId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GuestResponse"];
                };
            };
        };
    };
    importCsv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GuestImportResult"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GalleryAlbumResponse"][];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertAlbumRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GalleryAlbumResponse"];
                };
            };
        };
    };
    addPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                albumId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddPhotoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GalleryPhotoResponse"];
                };
            };
        };
    };
    list_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WeddingMemberResponse"][];
                };
            };
        };
    };
    invite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteCrewRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InviteCrewResponse"];
                };
            };
        };
    };
    checkIn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                guestId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInActionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CheckInGuestResponse"];
                };
            };
        };
    };
    seatFinder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeatFinderRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeatFinderResponse"];
                };
            };
        };
    };
    rsvpLookup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicRsvpLookupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PublicRsvpLookupResponse"];
                };
            };
        };
    };
    claim: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                giftId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimGiftRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GiftItemResponse"];
                };
            };
        };
    };
    contribute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                fundId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContributeCashRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CashContributionResponse"];
                };
            };
        };
    };
    guestContribute: {
        parameters: {
            query?: {
                caption?: string;
            };
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GalleryPhotoResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    hostRegistry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HostRegistryResponse"];
                };
            };
        };
    };
    export: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
        };
    };
    lookup: {
        parameters: {
            query?: {
                q?: string;
                token?: string;
            };
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CheckInGuestResponse"][];
                };
            };
        };
    };
    stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CheckInStatsResponse"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WeddingResponse"];
                };
            };
        };
    };
    members: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WeddingMemberResponse"][];
                };
            };
        };
    };
    getPublic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PublicWeddingResponse"];
                };
            };
        };
    };
    publicRegistry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PublicRegistryResponse"];
                };
            };
        };
    };
    publicGallery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GalleryAlbumResponse"][];
                };
            };
        };
    };
    get_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PublicInviteResponse"];
                };
            };
        };
    };
    publicCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PublicThankYouResponse"];
                };
            };
        };
    };
    getPublic_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    deletePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weddingId: number;
                photoId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
